### ISSUE TITLE
Readme mentions creds.json and pass.txt, but none are used

### ISSUE THREAD

**Issue by Zettt** [shanet/Google-Music-Playlist-Sync#5] opened 2016-01-25 16:16 UTC
The readme mentions two files a `creds.json` and a `pass.txt`. Both of which don't seem to be used at the moment. At least I couldn't find out how they are used. If you want to tinker with alternative setup methods, I'd suggest moving these files to a development branch, and only merge back to the main branch when the implementation is finished.

It's a bit confusing right now. :smile:

**Comment by Zettt** [comment] 2016-01-25 16:17
I think you can also remove the `-u` option. Right now it doesn't seem to be used. The script asks for username and pass when it's run.

**Comment by shanet** [comment] 2016-01-26 06:15
Hi Zettt, thanks for the feedback! I don't use Google Music anymore so I'm reliant on users to provide feedback here when stuff breaks.

To your points:
- Pass.txt: `pass.txt` was the first implementation on the credentials file. I apparently forgot to remove it from the README. Regardless, it has been removed.
- Cred file: The script will look for a file called `creds.json` in the current directory. I tested this and it appears to be working as intended. Please try again and let me know if that's not the case for you. If you're curious, the logic for this is in the `login_to_google_music` function on line 188 of the script.
- User option: Yup, the user argument was being ignored. This has been fixed in 9e4dd2b9a669e94f3370db58b8fddd7c4419c80a. Thanks!

**Comment by Zettt** [comment] 2016-01-26 09:26
@shanet Great. I'll check it out and let you know.

**Comment by Zettt** [comment] 2016-01-26 09:44
@shanet Seems to be working. The script says `Logging in` and then does something, so it appears that it can log in. Doesn't finish running though. Different issue, I suppose.

**Comment by Zettt** [comment] 2016-01-26 11:11
@shanet One more question. What's the `--root-dir` option supposed to do? I can't make sense of it. I find the description quite confusing.

**Comment by shanet** [comment] 2016-01-28 07:14
The root directory option is meant for M3U playlists that use a relative path. So if I have my music in `~/Music`, but am running this script from other directory, I can pass `~/Music` to be appended to all files in the M3U playlist.

**Closed as completed** 2016-07-29 06:20 UTC
